### ISSUE TITLE
'Error running filter pandoc-plantuml' following Development instructions. 

### ISSUE THREAD

**Issue by smrgeoinfo** [isamplesorg/isamplesorg.github.io#7]
Everything seemed ok until I got to 
`>isamplesorg.github.io>quarto preview`

then error messages:
```
Error running filter pandoc-plantuml:
Could not find executable pandoc-plantuml
```

looks like I need to install something more-- pandoc?

**Comment by smrgeoinfo** [comment]
update:
I'm on Windows 11 Home.

windows install pandoc-3.0.1-windows-x86_64.msi
didn't work
try activate quarto, cd to [isamples.github.io](http://isamples.github.io/) then
`pip install pandoc`
didn't work
update pip to v. 23.0
then
`pip install pandoc-plantuml-filter`
got further...
**isamplesorg.github.io>quarto preview**
```
Created directory plantuml-images
[ 1/13] about.qmd
[ 2/13] design\actors.md
[ 3/13] design\index.qmd
Created directory plantuml-images
Traceback (most recent call last):
....skip lines...
File "C:\Users\smrTu\AppData\Roaming\Python\Python310\site-packages\pandoc_plantuml_filter.py", line 39, in plantuml
    subprocess.check_call(PLANTUML_BIN.split() + ["-t" + filetype, src])
  File "C:\Program Files\Python310\lib\subprocess.py", line 364, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Program Files\Python310\lib\subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Program Files\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
Error running filter pandoc-plantuml:
Filter returned error status 1
```

**Comment by smrgeoinfo** [comment]
With more sleuthing find at https://github.com/timofurrer/pandoc-plantuml-filter 
`The PlantUML binary must be in your $PATH or can be set with the PLANTUML_BIN environment variable.
`
question is what is the plantUML binary-- where should the env variable point?   I have a 'pandoc_plantuml_filter.py' in AppData\Roaming\Python\Python310\site-packages. But that's python, not a binary.

**Comment by smrgeoinfo** [comment]
Have to get the Plantuml jar 
get plantuml.jar (Apache license) from https://plantuml.com/download
copy jar to {your file system path}
add PLANTUML_BIN as env variable =  "java -jar {your file system path}\plantuml.jar"  (note -- path should not have spaces...)

the quarto preview works now.   Not sure if just doing the plantuml.jar and env var fix would have solved the problem in the first place.
